import { Question } from "@/app/page";

export const QUESTIONS: Question[] = [
  {
    question: "How many pixels height is `h-36`?",
    answers: [
      { answer: "140px", isCorrect: false },
      { answer: "148px", isCorrect: false },
      { answer: "144px", isCorrect: true },
      { answer: "142px", isCorrect: false },
    ],
    correctAnswer: { answer: "144px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How many pixels height is `h-48`?",
    answers: [
      { answer: "184px", isCorrect: false },
      { answer: "180px", isCorrect: false },
      { answer: "188px", isCorrect: false },
      { answer: "192px", isCorrect: true },
    ],
    correctAnswer: { answer: "192px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the height in pixels of the class `h-64`?",
    answers: [
      { answer: "240px", isCorrect: false },
      { answer: "232px", isCorrect: false },
      { answer: "256px", isCorrect: true },
      { answer: "248px", isCorrect: false },
    ],
    correctAnswer: { answer: "256px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How tall is an element with the `h-12` class?",
    answers: [
      { answer: "40px", isCorrect: false },
      { answer: "48px", isCorrect: true },
      { answer: "44px", isCorrect: false },
      { answer: "42px", isCorrect: false },
    ],
    correctAnswer: { answer: "48px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the height in pixels of `h-20`?",
    answers: [
      { answer: "72px", isCorrect: false },
      { answer: "80px", isCorrect: true },
      { answer: "76px", isCorrect: false },
      { answer: "84px", isCorrect: false },
    ],
    correctAnswer: { answer: "80px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which height class corresponds to 32 pixels?",
    answers: [
      { answer: "h-10", isCorrect: false },
      { answer: "h-8", isCorrect: true },
      { answer: "h-12", isCorrect: false },
      { answer: "h-6", isCorrect: false },
    ],
    correctAnswer: { answer: "h-8", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the pixel height of the `h-96` class?",
    answers: [
      { answer: "368px", isCorrect: false },
      { answer: "384px", isCorrect: true },
      { answer: "376px", isCorrect: false },
      { answer: "392px", isCorrect: false },
    ],
    correctAnswer: { answer: "384px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How many pixels is the height of `h-72`?",
    answers: [
      { answer: "300px", isCorrect: false },
      { answer: "280px", isCorrect: false },
      { answer: "288px", isCorrect: true },
      { answer: "296px", isCorrect: false },
    ],
    correctAnswer: { answer: "288px", isCorrect: true },
    didAnswer: null,
  },

  {
    question: "Which class gives an element a height of 56 pixels?",
    answers: [
      { answer: "h-16", isCorrect: false },
      { answer: "h-14", isCorrect: true },
      { answer: "h-12", isCorrect: false },
      { answer: "h-10", isCorrect: false },
    ],
    correctAnswer: { answer: "h-14", isCorrect: true },
    didAnswer: null,
  },

  {
    question: "What height in pixels does `h-28` represent?",
    answers: [
      { answer: "104px", isCorrect: false },
      { answer: "116px", isCorrect: false },
      { answer: "112px", isCorrect: true },
      { answer: "108px", isCorrect: false },
    ],
    correctAnswer: { answer: "112px", isCorrect: true },
    didAnswer: null,
  },

  {
    question: "How many pixels is the height for the `h-80` class?",
    answers: [
      { answer: "304px", isCorrect: false },
      { answer: "312px", isCorrect: false },
      { answer: "320px", isCorrect: true },
      { answer: "328px", isCorrect: false },
    ],
    correctAnswer: { answer: "320px", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class is used to break a word mid-line?",
    answers: [
      { answer: "word-break", isCorrect: false },
      { answer: "break-all", isCorrect: false },
      { answer: "break-words", isCorrect: true },
      { answer: "word-wrap", isCorrect: false },
    ],
    correctAnswer: { answer: "break-words", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which utility class will set the line-height to 1?",
    answers: [
      { answer: "leading-none", isCorrect: true },
      { answer: "leading-tight", isCorrect: false },
      { answer: "leading-snug", isCorrect: false },
      { answer: "leading-loose", isCorrect: false },
    ],
    correctAnswer: { answer: "leading-none", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies the default line-height?",
    answers: [
      { answer: "leading-default", isCorrect: false },
      { answer: "leading-normal", isCorrect: true },
      { answer: "leading-base", isCorrect: false },
      { answer: "leading-regular", isCorrect: false },
    ],
    correctAnswer: { answer: "leading-normal", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class would you use for a line-height of 1.25?",
    answers: [
      { answer: "leading-snug", isCorrect: false },
      { answer: "leading-normal", isCorrect: false },
      { answer: "leading-tight", isCorrect: true },
      { answer: "leading-relaxed", isCorrect: false },
    ],
    correctAnswer: { answer: "leading-tight", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the line-height to 2?",
    answers: [
      { answer: "leading-wide", isCorrect: false },
      { answer: "leading-relaxed", isCorrect: false },
      { answer: "leading-loose", isCorrect: true },
      { answer: "leading-double", isCorrect: false },
    ],
    correctAnswer: { answer: "leading-loose", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the font size applied by the 'text-xl' class?",
    answers: [
      { answer: "1.5rem (24px)", isCorrect: false },
      { answer: "1rem (16px)", isCorrect: false },
      { answer: "1.75rem (28px)", isCorrect: false },
      { answer: "1.25rem (20px)", isCorrect: true },
    ],
    correctAnswer: { answer: "1.25rem (20px)", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a border radius of 0.5rem (8px)?",
    answers: [
      { answer: "rounded-sm", isCorrect: false },
      { answer: "rounded-md", isCorrect: true },
      { answer: "rounded-lg", isCorrect: false },
      { answer: "rounded", isCorrect: false },
    ],
    correctAnswer: { answer: "rounded-md", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class removes the border?",
    answers: [
      { answer: "border-none", isCorrect: true },
      { answer: "border-hidden", isCorrect: false },
      { answer: "border-solid", isCorrect: false },
      { answer: "border-clear", isCorrect: false },
    ],
    correctAnswer: { answer: "border-none", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the outline offset to 2px?",
    answers: [
      { answer: "outline-offset-2", isCorrect: true },
      { answer: "outline-offset-1", isCorrect: false },
      { answer: "outline-offset-sm", isCorrect: false },
      { answer: "outline-offset-xs", isCorrect: false },
    ],
    correctAnswer: { answer: "outline-offset-2", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the outline offset to 4px?",
    answers: [
      { answer: "outline-offset-md", isCorrect: false },
      { answer: "outline-offset-2", isCorrect: false },
      { answer: "outline-offset-lg", isCorrect: false },
      { answer: "outline-offset-4", isCorrect: true },
    ],
    correctAnswer: { answer: "outline-offset-4", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class removes all border radius?",
    answers: [
      { answer: "rounded-zero", isCorrect: false },
      { answer: "rounded-none", isCorrect: true },
      { answer: "rounded-sm", isCorrect: false },
      { answer: "rounded-clear", isCorrect: false },
    ],
    correctAnswer: { answer: "rounded-none", isCorrect: true },
    didAnswer: null,
  },
  {
    question:
      "Which class will allow words to break and add hyphens where needed?",
    answers: [
      { answer: "hyphens-manual", isCorrect: false },
      { answer: "hyphens-break", isCorrect: false },
      { answer: "hyphens-auto", isCorrect: true },
      { answer: "hyphens-none", isCorrect: false },
    ],
    correctAnswer: { answer: "hyphens-auto", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the effect of the 'hyphens-none' class?",
    answers: [
      { answer: "Prevents hyphenation of words", isCorrect: true },
      { answer: "Allows hyphenation only at manual breaks", isCorrect: false },
      {
        answer: "Forces hyphenation at all possible breakpoints",
        isCorrect: false,
      },
      { answer: "Adds hyphens to all words", isCorrect: false },
    ],
    correctAnswer: { answer: "Prevents hyphenation of words", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a letter-spacing of 0.05em?",
    answers: [
      { answer: "tracking-wide", isCorrect: false },
      { answer: "tracking-tighter", isCorrect: false },
      { answer: "tracking-wider", isCorrect: true },
      { answer: "tracking-tight", isCorrect: false },
    ],
    correctAnswer: { answer: "tracking-wider", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class would you use for a letter-spacing of -0.05em?",
    answers: [
      { answer: "tracking-tighter", isCorrect: false },
      { answer: "tracking-normal", isCorrect: false },
      { answer: "tracking-narrow", isCorrect: false },
      { answer: "tracking-tight", isCorrect: true },
    ],
    correctAnswer: { answer: "tracking-tight", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What does the class 'leading-snug' do?",
    answers: [
      { answer: "Sets line-height to 1.5", isCorrect: false },
      { answer: "Sets line-height to 1.375", isCorrect: true },
      { answer: "Sets line-height to 1.25", isCorrect: false },
      { answer: "Sets line-height to 1.75", isCorrect: false },
    ],
    correctAnswer: { answer: "Sets line-height to 1.375", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the line-height applied by 'leading-none'?",
    answers: [
      { answer: "line-height: 0", isCorrect: false },
      { answer: "line-height: 1.25", isCorrect: false },
      { answer: "line-height: 1", isCorrect: true },
      { answer: "line-height: 1.5", isCorrect: false },
    ],
    correctAnswer: { answer: "line-height: 1", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets an element's margin to 1rem?",
    answers: [
      { answer: "m-16", isCorrect: false },
      { answer: "m-8", isCorrect: false },
      { answer: "m-4", isCorrect: true },
      { answer: "m-2", isCorrect: false },
    ],
    correctAnswer: { answer: "m-4", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class is used for setting the width to full?",
    answers: [
      { answer: "w-100", isCorrect: false },
      { answer: "w-complete", isCorrect: false },
      { answer: "w-total", isCorrect: false },
      { answer: "w-full", isCorrect: true },
    ],
    correctAnswer: { answer: "w-full", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class makes the text bold?",
    answers: [
      { answer: "font-heavy", isCorrect: false },
      { answer: "font-strong", isCorrect: false },
      { answer: "font-thick", isCorrect: false },
      { answer: "font-bold", isCorrect: true },
    ],
    correctAnswer: { answer: "font-bold", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply a rounded border of 0.25rem?",
    answers: [
      { answer: "rounded-4", isCorrect: false },
      { answer: "rounded-quarter", isCorrect: false },
      { answer: "rounded-md", isCorrect: true },
      { answer: "rounded-0.25", isCorrect: false },
    ],
    correctAnswer: { answer: "rounded-md", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class adds a medium shadow effect?",
    answers: [
      { answer: "s-md", isCorrect: false },
      { answer: "shadow-md", isCorrect: true },
      { answer: "shadow-medium", isCorrect: false },
      { answer: "shadow-normal", isCorrect: false },
    ],
    correctAnswer: { answer: "shadow-md", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class adds an underline to text?",
    answers: [
      { answer: "text-underline", isCorrect: false },
      { answer: "decoration-under", isCorrect: false },
      { answer: "underline", isCorrect: true },
      { answer: "text-line-bottom", isCorrect: false },
    ],
    correctAnswer: { answer: "underline", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class makes an element's width 50% of its parent?",
    answers: [
      { answer: "w-50", isCorrect: false },
      { answer: "w-50%", isCorrect: false },
      { answer: "w-1/2", isCorrect: true },
      { answer: "w-half", isCorrect: false },
    ],
    correctAnswer: { answer: "w-1/2", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply a max-width of 768px?",
    answers: [
      { answer: "max-w-768", isCorrect: false },
      { answer: "max-w-medium", isCorrect: false },
      { answer: "max-w-lg", isCorrect: true },
      { answer: "max-w-tablet", isCorrect: false },
    ],
    correctAnswer: { answer: "max-w-lg", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you set a line-height of 1.5?",
    answers: [
      { answer: "leading-relaxed", isCorrect: true },
      { answer: "leading-tight", isCorrect: false },
      { answer: "line-height-1.5", isCorrect: false },
      { answer: "lh-1.5", isCorrect: false },
    ],
    correctAnswer: { answer: "leading-relaxed", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the border spacing to 4px?",
    answers: [
      { answer: "border-spacing-1", isCorrect: true },
      { answer: "border-spacing-2", isCorrect: false },
      { answer: "border-spacing-xs", isCorrect: false },
      { answer: "border-spacing-sm", isCorrect: false },
    ],
    correctAnswer: { answer: "border-spacing-1", isCorrect: true },
    didAnswer: null,
  },

  {
    question:
      "Which class would you use to shrink an element to half its original size?",
    answers: [
      { answer: "scale-50", isCorrect: true },
      { answer: "scale-75", isCorrect: false },
      { answer: "scale-100", isCorrect: false },
      { answer: "scale-25", isCorrect: false },
    ],
    correctAnswer: { answer: "scale-50", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply horizontal padding of 2rem?",
    answers: [
      { answer: "p-x-8", isCorrect: false },
      { answer: "padding-x-2", isCorrect: false },
      { answer: "px-8", isCorrect: true },
      { answer: "ph-2", isCorrect: false },
    ],
    correctAnswer: { answer: "px-8", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class is used for uppercase text?",
    answers: [
      { answer: "text-upper", isCorrect: false },
      { answer: "caps", isCorrect: false },
      { answer: "uppercase", isCorrect: true },
      { answer: "all-caps", isCorrect: false },
    ],
    correctAnswer: { answer: "uppercase", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply a border of 2px?",
    answers: [
      { answer: "border-width-2", isCorrect: false },
      { answer: "border-2px", isCorrect: false },
      { answer: "border-2", isCorrect: true },
      { answer: "b-2", isCorrect: false },
    ],
    correctAnswer: { answer: "border-2", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a red background?",
    answers: [
      { answer: "bg-red-default", isCorrect: false },
      { answer: "bg-red-medium", isCorrect: false },
      { answer: "bg-red-500", isCorrect: true },
      { answer: "background-red", isCorrect: false },
    ],
    correctAnswer: { answer: "bg-red-500", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you make text unselectable?",
    answers: [
      { answer: "no-select", isCorrect: false },
      { answer: "select-none", isCorrect: true },
      { answer: "unselectable", isCorrect: false },
      { answer: "prevent-select", isCorrect: false },
    ],
    correctAnswer: { answer: "select-none", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies 100% height?",
    answers: [
      { answer: "height-full", isCorrect: false },
      { answer: "h-100%", isCorrect: false },
      { answer: "h-full", isCorrect: true },
      { answer: "height-100", isCorrect: false },
    ],
    correctAnswer: { answer: "h-full", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies 100% width?",
    answers: [
      { answer: "width-full", isCorrect: false },
      { answer: "w-100%", isCorrect: false },
      { answer: "width-100", isCorrect: false },
      { answer: "w-full", isCorrect: true },
    ],
    correctAnswer: { answer: "w-full", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets an element to flex display?",
    answers: [
      { answer: "display-flex", isCorrect: false },
      { answer: "d-flex", isCorrect: false },
      { answer: "flex", isCorrect: true },
      { answer: "flexbox", isCorrect: false },
    ],
    correctAnswer: { answer: "flex", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What is the default display behavior of `hidden`?",
    answers: [
      { answer: "visibility: collapse;", isCorrect: false },
      { answer: "opacity: 0; visibility: hidden;", isCorrect: false },
      { answer: "display: none;", isCorrect: true },
      { answer: "position: absolute; left: -9999px;", isCorrect: false },
    ],
    correctAnswer: { answer: "display: none;", isCorrect: true },
    didAnswer: null,
  },
  {
    question:
      "Which utility class should be used to allow pinch-zoom and pan gestures in all directions?",
    answers: [
      { answer: "touch-manipulation", isCorrect: false },
      { answer: "touch-auto", isCorrect: true },
      { answer: "touch-pinch-zoom", isCorrect: false },
      { answer: "touch-pan-x touch-pan-y", isCorrect: false },
    ],
    correctAnswer: { answer: "touch-auto", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply padding on all sides of 1.5rem?",
    answers: [
      { answer: "p-1.5", isCorrect: false },
      { answer: "padding-6", isCorrect: false },
      { answer: "p-6", isCorrect: true },
      { answer: "p-24", isCorrect: false },
    ],
    correctAnswer: { answer: "p-6", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a white text color?",
    answers: [
      { answer: "color-white", isCorrect: false },
      { answer: "text-#fff", isCorrect: false },
      { answer: "text-white", isCorrect: true },
      { answer: "font-color-white", isCorrect: false },
    ],
    correctAnswer: { answer: "text-white", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What does `bg-opacity-50` do?",
    answers: [
      { answer: "Sets element opacity to 50%", isCorrect: false },
      { answer: "Sets background opacity to 50%", isCorrect: true },
      { answer: "Applies a 50% transparent overlay", isCorrect: false },
      { answer: "Reduces color intensity by 50%", isCorrect: false },
    ],
    correctAnswer: {
      answer: "Sets background opacity to 50%",
      isCorrect: true,
    },
    didAnswer: null,
  },
  {
    question: "How do you add a gap of 1rem between flex items?",
    answers: [
      { answer: "x-4", isCorrect: false },
      { answer: "flex-gap-4", isCorrect: false },
      { answer: "gap-4", isCorrect: true },
      { answer: "item-spacing-4", isCorrect: false },
    ],
    correctAnswer: { answer: "gap-4", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets a max-height of 16rem?",
    answers: [
      { answer: "mh-64", isCorrect: false },
      { answer: "max-height-16", isCorrect: false },
      { answer: "max-h-64", isCorrect: true },
      { answer: "height-max-16", isCorrect: false },
    ],
    correctAnswer: { answer: "max-h-64", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What does `rounded-full` do?",
    answers: [
      { answer: "Creates a circular svg shape", isCorrect: false },
      { answer: "Applies maximum border-radius", isCorrect: true },
      { answer: "Rounds all corners to 9px", isCorrect: false },
      { answer: "Makes elements square", isCorrect: false },
    ],
    correctAnswer: {
      answer: "Applies maximum border-radius",
      isCorrect: true,
    },
    didAnswer: null,
  },

  {
    question: "How do you apply rounded corners on the top side only?",
    answers: [
      { answer: "r-top", isCorrect: true },
      { answer: "rounded-t-md", isCorrect: false },
      { answer: "rounded-top-md", isCorrect: false },
      { answer: "rounded-md", isCorrect: false },
    ],
    correctAnswer: { answer: "rounded-t", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class adds a black border?",
    answers: [
      { answer: "border-fuchsia-900", isCorrect: false },
      { answer: "border-black", isCorrect: true },
      { answer: "border-heavy", isCorrect: false },
      { answer: "border-dark", isCorrect: false },
    ],
    correctAnswer: { answer: "border-black", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class makes an element's background color green?",
    answers: [
      { answer: "background-green", isCorrect: false },
      { answer: "bg-light-green", isCorrect: false },
      { answer: "bg-green-300", isCorrect: true },
      { answer: "bg-green-dark", isCorrect: false },
    ],
    correctAnswer: { answer: "bg-green-300", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class is used to apply a rounded border radius?",
    answers: [
      { answer: "border-radius-md", isCorrect: false },
      { answer: "rounded-md", isCorrect: true },
      { answer: "rounded-large", isCorrect: false },
      { answer: "radius-md", isCorrect: false },
    ],
    correctAnswer: { answer: "rounded-md", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a shadow effect to an element?",
    answers: [
      { answer: "shadow-heavy", isCorrect: false },
      { answer: "shadow-lg", isCorrect: true },
      { answer: "shadow-large", isCorrect: false },
      { answer: "shadow-light", isCorrect: false },
    ],
    correctAnswer: { answer: "shadow-lg", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the width to full?",
    answers: [
      { answer: "w-full", isCorrect: true },
      { answer: "width-full", isCorrect: false },
      { answer: "w-100", isCorrect: false },
      { answer: "full-width", isCorrect: false },
    ],
    correctAnswer: { answer: "w-full", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class is used to add a linear gradient background?",
    answers: [
      { answer: "bg-gradient", isCorrect: false },
      { answer: "bg-gradient-to-r", isCorrect: true },
      { answer: "gradient-r", isCorrect: false },
      { answer: "bg-gradient-linear", isCorrect: false },
    ],
    correctAnswer: { answer: "bg-gradient-to-r", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class applies a grid layout with two columns?",
    answers: [
      { answer: "grid-layout-2", isCorrect: false },
      { answer: "grid-cols-2", isCorrect: true },
      { answer: "cols-2", isCorrect: false },
      { answer: "grid-2-cols", isCorrect: false },
    ],
    correctAnswer: { answer: "grid-cols-2", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class sets the z-index of an element to a high value?",
    answers: [
      { answer: "z-high", isCorrect: false },
      { answer: "z-100", isCorrect: false },
      { answer: "z-top", isCorrect: false },
      { answer: "z-50", isCorrect: true },
    ],
    correctAnswer: { answer: "z-50", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class makes an element's border color transparent?",
    answers: [
      { answer: "border-none", isCorrect: false },
      { answer: "border-clear", isCorrect: false },
      { answer: "border-transparent", isCorrect: true },
      { answer: "border-opacity-0", isCorrect: false },
    ],
    correctAnswer: { answer: "border-transparent", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class controls the opacity of an element?",
    answers: [
      { answer: "transparency-75", isCorrect: false },
      { answer: "opacity-high", isCorrect: false },
      { answer: "visibility-75", isCorrect: false },
      { answer: "opacity-75", isCorrect: true },
    ],
    correctAnswer: { answer: "opacity-75", isCorrect: true },
    didAnswer: null,
  },
  {
    question:
      "Which class applies a transition effect to an element's opacity?",
    answers: [
      { answer: "opacity-transition", isCorrect: false },
      { answer: "fade-transition", isCorrect: false },
      { answer: "transition-opacity", isCorrect: true },
      { answer: "transition-opacity-effect", isCorrect: false },
    ],
    correctAnswer: { answer: "transition-opacity", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class is used to change the cursor to a pointer?",
    answers: [
      { answer: "pointer-cursor", isCorrect: false },
      { answer: "cursor-pointer", isCorrect: true },
      { answer: "cursor-hand", isCorrect: false },
      { answer: "clickable", isCorrect: false },
    ],
    correctAnswer: { answer: "cursor-pointer", isCorrect: true },
    didAnswer: null,
  },
  {
    question:
      "What class applies padding only to the right side of an element?",
    answers: [
      { answer: "padding-right-4", isCorrect: false },
      { answer: "px-4", isCorrect: false },
      { answer: "pr-4", isCorrect: true },
      { answer: "padding-r-4", isCorrect: false },
    ],
    correctAnswer: { answer: "pr-4", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class sets the opacity of an element to 50%?",
    answers: [
      { answer: "opacity-0.5", isCorrect: false },
      { answer: "transparency-50", isCorrect: false },
      { answer: "opacity-50", isCorrect: true },
      { answer: "alpha-50", isCorrect: false },
    ],
    correctAnswer: { answer: "opacity-50", isCorrect: true },
    didAnswer: null,
  },
  {
    question:
      "Which class should you use to set the overflow behavior of an element to scroll only when needed?",
    answers: [
      { answer: "overflow-auto", isCorrect: true },
      { answer: "overflow-scroll", isCorrect: false },
      { answer: "overflow-hidden", isCorrect: false },
      { answer: "scroll-auto", isCorrect: false },
    ],
    correctAnswer: { answer: "overflow-auto", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class sets a fixed width of 3rem for an element?",
    answers: [
      { answer: "w-12", isCorrect: true },
      { answer: "width-3rem", isCorrect: false },
      { answer: "w-3rem", isCorrect: false },
      { answer: "w-48", isCorrect: false },
    ],
    correctAnswer: { answer: "w-12", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What class applies a 2-pixel border width?",
    answers: [
      { answer: "border-width-2", isCorrect: false },
      { answer: "border-thin", isCorrect: false },
      { answer: "border-2", isCorrect: true },
      { answer: "border-medium", isCorrect: false },
    ],
    correctAnswer: { answer: "border-2", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "Which class adds padding on the top and bottom only?",
    answers: [
      { answer: "px-4", isCorrect: false },
      { answer: "py-4", isCorrect: true },
      { answer: "padding-md", isCorrect: false },
      { answer: "padding-4", isCorrect: false },
    ],
    correctAnswer: { answer: "py-4", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "How do you apply a blur effect of 4px?",
    answers: [
      { answer: "blur-md", isCorrect: false },
      { answer: "blur-sm", isCorrect: true },
      { answer: "blur-lg", isCorrect: false },
      { answer: "blur-none", isCorrect: false },
    ],
    correctAnswer: { answer: "blur-sm", isCorrect: true },
    didAnswer: null,
  },
  {
    question: "What does `text-stone-500` apply?",
    answers: [
      { answer: "Applies a brown-ish text color", isCorrect: false },
      { answer: "Applies a red-ish text color", isCorrect: true },
      { answer: "Applies a gray-ish text color", isCorrect: false },
      { answer: "Applies a black text color", isCorrect: false },
    ],
    correctAnswer: {
      answer: "Applies a medium-gray text color",
      isCorrect: true,
    },
    didAnswer: null,
  },
];
